version: 2
jobs:
  build:
    working_directory: ~/project/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run: bundle install
      - run: bundle exec fastlane test
      - store_test_results:
          path: ~/project/android/reports
